// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/appointment/v1/appointment.proto

package appointmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppointmentStatus int32

const (
	AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED AppointmentStatus = 0
	AppointmentStatus_APPOINTMENT_STATUS_SCHEDULED   AppointmentStatus = 1
	AppointmentStatus_APPOINTMENT_STATUS_CANCELLED   AppointmentStatus = 2
	AppointmentStatus_APPOINTMENT_STATUS_COMPLETED   AppointmentStatus = 3
)

// Enum value maps for AppointmentStatus.
var (
	AppointmentStatus_name = map[int32]string{
		0: "APPOINTMENT_STATUS_UNSPECIFIED",
		1: "APPOINTMENT_STATUS_SCHEDULED",
		2: "APPOINTMENT_STATUS_CANCELLED",
		3: "APPOINTMENT_STATUS_COMPLETED",
	}
	AppointmentStatus_value = map[string]int32{
		"APPOINTMENT_STATUS_UNSPECIFIED": 0,
		"APPOINTMENT_STATUS_SCHEDULED":   1,
		"APPOINTMENT_STATUS_CANCELLED":   2,
		"APPOINTMENT_STATUS_COMPLETED":   3,
	}
)

func (x AppointmentStatus) Enum() *AppointmentStatus {
	p := new(AppointmentStatus)
	*p = x
	return p
}

func (x AppointmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_appointment_v1_appointment_proto_enumTypes[0].Descriptor()
}

func (AppointmentStatus) Type() protoreflect.EnumType {
	return &file_proto_appointment_v1_appointment_proto_enumTypes[0]
}

func (x AppointmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentStatus.Descriptor instead.
func (AppointmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{0}
}

type RecurrenceFrequency int32

const (
	RecurrenceFrequency_RECURRENCE_FREQUENCY_UNSPECIFIED RecurrenceFrequency = 0
	RecurrenceFrequency_RECURRENCE_FREQUENCY_DAILY       RecurrenceFrequency = 1
	RecurrenceFrequency_RECURRENCE_FREQUENCY_WEEKLY      RecurrenceFrequency = 2
	RecurrenceFrequency_RECURRENCE_FREQUENCY_MONTHLY     RecurrenceFrequency = 3
)

// Enum value maps for RecurrenceFrequency.
var (
	RecurrenceFrequency_name = map[int32]string{
		0: "RECURRENCE_FREQUENCY_UNSPECIFIED",
		1: "RECURRENCE_FREQUENCY_DAILY",
		2: "RECURRENCE_FREQUENCY_WEEKLY",
		3: "RECURRENCE_FREQUENCY_MONTHLY",
	}
	RecurrenceFrequency_value = map[string]int32{
		"RECURRENCE_FREQUENCY_UNSPECIFIED": 0,
		"RECURRENCE_FREQUENCY_DAILY":       1,
		"RECURRENCE_FREQUENCY_WEEKLY":      2,
		"RECURRENCE_FREQUENCY_MONTHLY":     3,
	}
)

func (x RecurrenceFrequency) Enum() *RecurrenceFrequency {
	p := new(RecurrenceFrequency)
	*p = x
	return p
}

func (x RecurrenceFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecurrenceFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_appointment_v1_appointment_proto_enumTypes[1].Descriptor()
}

func (RecurrenceFrequency) Type() protoreflect.EnumType {
	return &file_proto_appointment_v1_appointment_proto_enumTypes[1]
}

func (x RecurrenceFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecurrenceFrequency.Descriptor instead.
func (RecurrenceFrequency) EnumDescriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{1}
}

type AppointmentEvent_EventType int32

const (
	AppointmentEvent_EVENT_TYPE_UNSPECIFIED AppointmentEvent_EventType = 0
	AppointmentEvent_EVENT_TYPE_CREATED     AppointmentEvent_EventType = 1
	AppointmentEvent_EVENT_TYPE_UPDATED     AppointmentEvent_EventType = 2
	AppointmentEvent_EVENT_TYPE_DELETED     AppointmentEvent_EventType = 3
)

// Enum value maps for AppointmentEvent_EventType.
var (
	AppointmentEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_CREATED",
		2: "EVENT_TYPE_UPDATED",
		3: "EVENT_TYPE_DELETED",
	}
	AppointmentEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_CREATED":     1,
		"EVENT_TYPE_UPDATED":     2,
		"EVENT_TYPE_DELETED":     3,
	}
)

func (x AppointmentEvent_EventType) Enum() *AppointmentEvent_EventType {
	p := new(AppointmentEvent_EventType)
	*p = x
	return p
}

func (x AppointmentEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_appointment_v1_appointment_proto_enumTypes[2].Descriptor()
}

func (AppointmentEvent_EventType) Type() protoreflect.EnumType {
	return &file_proto_appointment_v1_appointment_proto_enumTypes[2]
}

func (x AppointmentEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentEvent_EventType.Descriptor instead.
func (AppointmentEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{16, 0}
}

type Appointment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,8,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,9,opt,name=status,proto3,enum=appointment.v1.AppointmentStatus" json:"status,omitempty"`
	Recurrence    *RecurrenceRule        `protobuf:"bytes,10,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int64                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Appointment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Appointment) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Appointment) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Appointment) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Appointment) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *Appointment) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

func (x *Appointment) GetRecurrence() *RecurrenceRule {
	if x != nil {
		return x.Recurrence
	}
	return nil
}

func (x *Appointment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Appointment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Appointment) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RecurrenceRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     RecurrenceFrequency    `protobuf:"varint,1,opt,name=frequency,proto3,enum=appointment.v1.RecurrenceFrequency" json:"frequency,omitempty"`
	Interval      int32                  `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecurrenceRule) Reset() {
	*x = RecurrenceRule{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecurrenceRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecurrenceRule) ProtoMessage() {}

func (x *RecurrenceRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecurrenceRule.ProtoReflect.Descriptor instead.
func (*RecurrenceRule) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *RecurrenceRule) GetFrequency() RecurrenceFrequency {
	if x != nil {
		return x.Frequency
	}
	return RecurrenceFrequency_RECURRENCE_FREQUENCY_UNSPECIFIED
}

func (x *RecurrenceRule) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *RecurrenceRule) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *RecurrenceRule) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ConflictInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ConflictingAppointments []*Appointment         `protobuf:"bytes,1,rep,name=conflicting_appointments,json=conflictingAppointments,proto3" json:"conflicting_appointments,omitempty"`
	Message                 string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConflictInfo) Reset() {
	*x = ConflictInfo{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictInfo) ProtoMessage() {}

func (x *ConflictInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictInfo.ProtoReflect.Descriptor instead.
func (*ConflictInfo) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *ConflictInfo) GetConflictingAppointments() []*Appointment {
	if x != nil {
		return x.ConflictingAppointments
	}
	return nil
}

func (x *ConflictInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,7,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Recurrence    *RecurrenceRule        `protobuf:"bytes,8,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAppointmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAppointmentRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateAppointmentRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateAppointmentRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateAppointmentRequest) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *CreateAppointmentRequest) GetRecurrence() *RecurrenceRule {
	if x != nil {
		return x.Recurrence
	}
	return nil
}

type CreateAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	Conflicts     *ConflictInfo          `protobuf:"bytes,2,opt,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentResponse) Reset() {
	*x = CreateAppointmentResponse{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentResponse) ProtoMessage() {}

func (x *CreateAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentResponse.ProtoReflect.Descriptor instead.
func (*CreateAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

func (x *CreateAppointmentResponse) GetConflicts() *ConflictInfo {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentResponse) Reset() {
	*x = GetAppointmentResponse{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentResponse) ProtoMessage() {}

func (x *GetAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *GetAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type ListAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Status        AppointmentStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=appointment.v1.AppointmentStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{7}
}

func (x *ListAppointmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAppointmentsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListAppointmentsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListAppointmentsRequest) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

func (x *ListAppointmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAppointmentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{8}
}

func (x *ListAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type UpdateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentRequest) Reset() {
	*x = UpdateAppointmentRequest{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentRequest) ProtoMessage() {}

func (x *UpdateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAppointmentRequest) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type UpdateAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	Conflicts     *ConflictInfo          `protobuf:"bytes,2,opt,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentResponse) Reset() {
	*x = UpdateAppointmentResponse{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentResponse) ProtoMessage() {}

func (x *UpdateAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

func (x *UpdateAppointmentResponse) GetConflicts() *ConflictInfo {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type DeleteAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentRequest) Reset() {
	*x = DeleteAppointmentRequest{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentRequest) ProtoMessage() {}

func (x *DeleteAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentResponse) Reset() {
	*x = DeleteAppointmentResponse{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentResponse) ProtoMessage() {}

func (x *DeleteAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{12}
}

type CheckConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ExcludeId     string                 `protobuf:"bytes,4,opt,name=exclude_id,json=excludeId,proto3" json:"exclude_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConflictsRequest) Reset() {
	*x = CheckConflictsRequest{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConflictsRequest) ProtoMessage() {}

func (x *CheckConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConflictsRequest.ProtoReflect.Descriptor instead.
func (*CheckConflictsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{13}
}

func (x *CheckConflictsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckConflictsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CheckConflictsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CheckConflictsRequest) GetExcludeId() string {
	if x != nil {
		return x.ExcludeId
	}
	return ""
}

type CheckConflictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conflicts     *ConflictInfo          `protobuf:"bytes,1,opt,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConflictsResponse) Reset() {
	*x = CheckConflictsResponse{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConflictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConflictsResponse) ProtoMessage() {}

func (x *CheckConflictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConflictsResponse.ProtoReflect.Descriptor instead.
func (*CheckConflictsResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{14}
}

func (x *CheckConflictsResponse) GetConflicts() *ConflictInfo {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type StreamAppointmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAppointmentsRequest) Reset() {
	*x = StreamAppointmentsRequest{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAppointmentsRequest) ProtoMessage() {}

func (x *StreamAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*StreamAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{15}
}

func (x *StreamAppointmentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AppointmentEvent struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          AppointmentEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=appointment.v1.AppointmentEvent_EventType" json:"type,omitempty"`
	Appointment   *Appointment               `protobuf:"bytes,2,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentEvent) Reset() {
	*x = AppointmentEvent{}
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentEvent) ProtoMessage() {}

func (x *AppointmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_v1_appointment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentEvent.ProtoReflect.Descriptor instead.
func (*AppointmentEvent) Descriptor() ([]byte, []int) {
	return file_proto_appointment_v1_appointment_proto_rawDescGZIP(), []int{16}
}

func (x *AppointmentEvent) GetType() AppointmentEvent_EventType {
	if x != nil {
		return x.Type
	}
	return AppointmentEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *AppointmentEvent) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

var File_proto_appointment_v1_appointment_proto protoreflect.FileDescriptor

const file_proto_appointment_v1_appointment_proto_rawDesc = "" +
	"\n" +
	"&proto/appointment/v1/appointment.proto\x12\x0eappointment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x04\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\b \x03(\tR\tattendees\x129\n" +
	"\x06status\x18\t \x01(\x0e2!.appointment.v1.AppointmentStatusR\x06status\x12>\n" +
	"\n" +
	"recurrence\x18\n" +
	" \x01(\v2\x1e.appointment.v1.RecurrenceRuleR\n" +
	"recurrence\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\r \x01(\x03R\aversion\"\xb7\x01\n" +
	"\x0eRecurrenceRule\x12A\n" +
	"\tfrequency\x18\x01 \x01(\x0e2#.appointment.v1.RecurrenceFrequencyR\tfrequency\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\x05R\binterval\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"\x80\x01\n" +
	"\fConflictInfo\x12V\n" +
	"\x18conflicting_appointments\x18\x01 \x03(\v2\x1b.appointment.v1.AppointmentR\x17conflictingAppointments\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd7\x02\n" +
	"\x18CreateAppointmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\a \x03(\tR\tattendees\x12>\n" +
	"\n" +
	"recurrence\x18\b \x01(\v2\x1e.appointment.v1.RecurrenceRuleR\n" +
	"recurrence\"\x96\x01\n" +
	"\x19CreateAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\x12:\n" +
	"\tconflicts\x18\x02 \x01(\v2\x1c.appointment.v1.ConflictInfoR\tconflicts\"'\n" +
	"\x15GetAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x16GetAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"\xf7\x01\n" +
	"\x17ListAppointmentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.appointment.v1.AppointmentStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"[\n" +
	"\x18ListAppointmentsResponse\x12?\n" +
	"\fappointments\x18\x01 \x03(\v2\x1b.appointment.v1.AppointmentR\fappointments\"Y\n" +
	"\x18UpdateAppointmentRequest\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"\x96\x01\n" +
	"\x19UpdateAppointmentResponse\x12=\n" +
	"\vappointment\x18\x01 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\x12:\n" +
	"\tconflicts\x18\x02 \x01(\v2\x1c.appointment.v1.ConflictInfoR\tconflicts\"*\n" +
	"\x18DeleteAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteAppointmentResponse\"\xc1\x01\n" +
	"\x15CheckConflictsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"exclude_id\x18\x04 \x01(\tR\texcludeId\"T\n" +
	"\x16CheckConflictsResponse\x12:\n" +
	"\tconflicts\x18\x01 \x01(\v2\x1c.appointment.v1.ConflictInfoR\tconflicts\"4\n" +
	"\x19StreamAppointmentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x82\x02\n" +
	"\x10AppointmentEvent\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.appointment.v1.AppointmentEvent.EventTypeR\x04type\x12=\n" +
	"\vappointment\x18\x02 \x01(\v2\x1b.appointment.v1.AppointmentR\vappointment\"o\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_CREATED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_UPDATED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x03*\x9d\x01\n" +
	"\x11AppointmentStatus\x12\"\n" +
	"\x1eAPPOINTMENT_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_SCHEDULED\x10\x01\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_CANCELLED\x10\x02\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_COMPLETED\x10\x03*\x9e\x01\n" +
	"\x13RecurrenceFrequency\x12$\n" +
	" RECURRENCE_FREQUENCY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRECURRENCE_FREQUENCY_DAILY\x10\x01\x12\x1f\n" +
	"\x1bRECURRENCE_FREQUENCY_WEEKLY\x10\x02\x12 \n" +
	"\x1cRECURRENCE_FREQUENCY_MONTHLY\x10\x032\xe0\x05\n" +
	"\x12AppointmentService\x12h\n" +
	"\x11CreateAppointment\x12(.appointment.v1.CreateAppointmentRequest\x1a).appointment.v1.CreateAppointmentResponse\x12_\n" +
	"\x0eGetAppointment\x12%.appointment.v1.GetAppointmentRequest\x1a&.appointment.v1.GetAppointmentResponse\x12e\n" +
	"\x10ListAppointments\x12'.appointment.v1.ListAppointmentsRequest\x1a(.appointment.v1.ListAppointmentsResponse\x12h\n" +
	"\x11UpdateAppointment\x12(.appointment.v1.UpdateAppointmentRequest\x1a).appointment.v1.UpdateAppointmentResponse\x12h\n" +
	"\x11DeleteAppointment\x12(.appointment.v1.DeleteAppointmentRequest\x1a).appointment.v1.DeleteAppointmentResponse\x12_\n" +
	"\x0eCheckConflicts\x12%.appointment.v1.CheckConflictsRequest\x1a&.appointment.v1.CheckConflictsResponse\x12c\n" +
	"\x12StreamAppointments\x12).appointment.v1.StreamAppointmentsRequest\x1a .appointment.v1.AppointmentEvent0\x01BFZDschedule-management-system/server/proto/appointment/v1;appointmentv1b\x06proto3"

var (
	file_proto_appointment_v1_appointment_proto_rawDescOnce sync.Once
	file_proto_appointment_v1_appointment_proto_rawDescData []byte
)

func file_proto_appointment_v1_appointment_proto_rawDescGZIP() []byte {
	file_proto_appointment_v1_appointment_proto_rawDescOnce.Do(func() {
		file_proto_appointment_v1_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appointment_v1_appointment_proto_rawDesc), len(file_proto_appointment_v1_appointment_proto_rawDesc)))
	})
	return file_proto_appointment_v1_appointment_proto_rawDescData
}

var file_proto_appointment_v1_appointment_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_appointment_v1_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_appointment_v1_appointment_proto_goTypes = []any{
	(AppointmentStatus)(0),            // 0: appointment.v1.AppointmentStatus
	(RecurrenceFrequency)(0),          // 1: appointment.v1.RecurrenceFrequency
	(AppointmentEvent_EventType)(0),   // 2: appointment.v1.AppointmentEvent.EventType
	(*Appointment)(nil),               // 3: appointment.v1.Appointment
	(*RecurrenceRule)(nil),            // 4: appointment.v1.RecurrenceRule
	(*ConflictInfo)(nil),              // 5: appointment.v1.ConflictInfo
	(*CreateAppointmentRequest)(nil),  // 6: appointment.v1.CreateAppointmentRequest
	(*CreateAppointmentResponse)(nil), // 7: appointment.v1.CreateAppointmentResponse
	(*GetAppointmentRequest)(nil),     // 8: appointment.v1.GetAppointmentRequest
	(*GetAppointmentResponse)(nil),    // 9: appointment.v1.GetAppointmentResponse
	(*ListAppointmentsRequest)(nil),   // 10: appointment.v1.ListAppointmentsRequest
	(*ListAppointmentsResponse)(nil),  // 11: appointment.v1.ListAppointmentsResponse
	(*UpdateAppointmentRequest)(nil),  // 12: appointment.v1.UpdateAppointmentRequest
	(*UpdateAppointmentResponse)(nil), // 13: appointment.v1.UpdateAppointmentResponse
	(*DeleteAppointmentRequest)(nil),  // 14: appointment.v1.DeleteAppointmentRequest
	(*DeleteAppointmentResponse)(nil), // 15: appointment.v1.DeleteAppointmentResponse
	(*CheckConflictsRequest)(nil),     // 16: appointment.v1.CheckConflictsRequest
	(*CheckConflictsResponse)(nil),    // 17: appointment.v1.CheckConflictsResponse
	(*StreamAppointmentsRequest)(nil), // 18: appointment.v1.StreamAppointmentsRequest
	(*AppointmentEvent)(nil),          // 19: appointment.v1.AppointmentEvent
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
}
var file_proto_appointment_v1_appointment_proto_depIdxs = []int32{
	20, // 0: appointment.v1.Appointment.start_time:type_name -> google.protobuf.Timestamp
	20, // 1: appointment.v1.Appointment.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: appointment.v1.Appointment.status:type_name -> appointment.v1.AppointmentStatus
	4,  // 3: appointment.v1.Appointment.recurrence:type_name -> appointment.v1.RecurrenceRule
	20, // 4: appointment.v1.Appointment.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: appointment.v1.Appointment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: appointment.v1.RecurrenceRule.frequency:type_name -> appointment.v1.RecurrenceFrequency
	20, // 7: appointment.v1.RecurrenceRule.until:type_name -> google.protobuf.Timestamp
	3,  // 8: appointment.v1.ConflictInfo.conflicting_appointments:type_name -> appointment.v1.Appointment
	20, // 9: appointment.v1.CreateAppointmentRequest.start_time:type_name -> google.protobuf.Timestamp
	20, // 10: appointment.v1.CreateAppointmentRequest.end_time:type_name -> google.protobuf.Timestamp
	4,  // 11: appointment.v1.CreateAppointmentRequest.recurrence:type_name -> appointment.v1.RecurrenceRule
	3,  // 12: appointment.v1.CreateAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	5,  // 13: appointment.v1.CreateAppointmentResponse.conflicts:type_name -> appointment.v1.ConflictInfo
	3,  // 14: appointment.v1.GetAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	20, // 15: appointment.v1.ListAppointmentsRequest.from:type_name -> google.protobuf.Timestamp
	20, // 16: appointment.v1.ListAppointmentsRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 17: appointment.v1.ListAppointmentsRequest.status:type_name -> appointment.v1.AppointmentStatus
	3,  // 18: appointment.v1.ListAppointmentsResponse.appointments:type_name -> appointment.v1.Appointment
	3,  // 19: appointment.v1.UpdateAppointmentRequest.appointment:type_name -> appointment.v1.Appointment
	3,  // 20: appointment.v1.UpdateAppointmentResponse.appointment:type_name -> appointment.v1.Appointment
	5,  // 21: appointment.v1.UpdateAppointmentResponse.conflicts:type_name -> appointment.v1.ConflictInfo
	20, // 22: appointment.v1.CheckConflictsRequest.start_time:type_name -> google.protobuf.Timestamp
	20, // 23: appointment.v1.CheckConflictsRequest.end_time:type_name -> google.protobuf.Timestamp
	5,  // 24: appointment.v1.CheckConflictsResponse.conflicts:type_name -> appointment.v1.ConflictInfo
	2,  // 25: appointment.v1.AppointmentEvent.type:type_name -> appointment.v1.AppointmentEvent.EventType
	3,  // 26: appointment.v1.AppointmentEvent.appointment:type_name -> appointment.v1.Appointment
	6,  // 27: appointment.v1.AppointmentService.CreateAppointment:input_type -> appointment.v1.CreateAppointmentRequest
	8,  // 28: appointment.v1.AppointmentService.GetAppointment:input_type -> appointment.v1.GetAppointmentRequest
	10, // 29: appointment.v1.AppointmentService.ListAppointments:input_type -> appointment.v1.ListAppointmentsRequest
	12, // 30: appointment.v1.AppointmentService.UpdateAppointment:input_type -> appointment.v1.UpdateAppointmentRequest
	14, // 31: appointment.v1.AppointmentService.DeleteAppointment:input_type -> appointment.v1.DeleteAppointmentRequest
	16, // 32: appointment.v1.AppointmentService.CheckConflicts:input_type -> appointment.v1.CheckConflictsRequest
	18, // 33: appointment.v1.AppointmentService.StreamAppointments:input_type -> appointment.v1.StreamAppointmentsRequest
	7,  // 34: appointment.v1.AppointmentService.CreateAppointment:output_type -> appointment.v1.CreateAppointmentResponse
	9,  // 35: appointment.v1.AppointmentService.GetAppointment:output_type -> appointment.v1.GetAppointmentResponse
	11, // 36: appointment.v1.AppointmentService.ListAppointments:output_type -> appointment.v1.ListAppointmentsResponse
	13, // 37: appointment.v1.AppointmentService.UpdateAppointment:output_type -> appointment.v1.UpdateAppointmentResponse
	15, // 38: appointment.v1.AppointmentService.DeleteAppointment:output_type -> appointment.v1.DeleteAppointmentResponse
	17, // 39: appointment.v1.AppointmentService.CheckConflicts:output_type -> appointment.v1.CheckConflictsResponse
	19, // 40: appointment.v1.AppointmentService.StreamAppointments:output_type -> appointment.v1.AppointmentEvent
	34, // [34:41] is the sub-list for method output_type
	27, // [27:34] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_appointment_v1_appointment_proto_init() }
func file_proto_appointment_v1_appointment_proto_init() {
	if File_proto_appointment_v1_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appointment_v1_appointment_proto_rawDesc), len(file_proto_appointment_v1_appointment_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appointment_v1_appointment_proto_goTypes,
		DependencyIndexes: file_proto_appointment_v1_appointment_proto_depIdxs,
		EnumInfos:         file_proto_appointment_v1_appointment_proto_enumTypes,
		MessageInfos:      file_proto_appointment_v1_appointment_proto_msgTypes,
	}.Build()
	File_proto_appointment_v1_appointment_proto = out.File
	file_proto_appointment_v1_appointment_proto_goTypes = nil
	file_proto_appointment_v1_appointment_proto_depIdxs = nil
}
